---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
  name: {{ include "mammal.name" . }}-ing
  labels:
    {{- include "mammal.labels" . | nindent 4 }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.hostname }}
    http:
      paths:
      - path: /mammal(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ include "mammal.name" . }}-svc
            port:
              number: {{ .Values.service.port }}
