---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mammal.name" . }}-svc
  labels:
    {{- include "mammal.labels" . | nindent 4 }}
spec:
  ports:
    -
      port: {{ .Values.service.port }}
      targetPort: 8000
  selector:
    {{- include "mammal.selectorLabels" . | nindent 4 }}
  type: LoadBalancer
